### ISSUE TITLE
run in background

### ISSUE THREAD

**Issue by mrdarkerr** [Poryaei/TapSwap-Clicker#15]
I run the script in Python as below in the background

python clicker.py & 

But with the passage of time, the time of the next click will change to a negative number and it will become a bug and no more clicks will work

How can I run the script in the background of my Ubuntu server without problems?

**Comment by M-logique** [comment]
This is due to TapSwap constantly disconnecting and reconnecting, and you have to restart the script every so often.

**Comment by mrdarkerr** [comment]
I have a suggestion that makes this script unique, consider a one-hour or two-hour time for the script to receive a new url from the bot so that the session is updated and does not suffer from possible bugs.

**Comment by Poryaei** [comment]
Could you please test the script again? I think the problem might have been fixed.

**Comment by Poryaei** [comment]
@mrdarkerr

**Comment by BraveCanister** [comment]
Will this result in me losing the coins like with notcoin? :D
