### ISSUE TITLE
UnboundLocalError: cannot access local variable 'energy_level' where it is not associated with a value

### ISSUE THREAD

**Issue by yopiucing** [Poryaei/TapSwap-Clicker#17]
![Screenshot_2024-05-28-15-48-40-09_84d3000e3f4017145260f7618db1d683](https://github.com/Poryaei/TapSwap-Clicker/assets/116066417/f7ff113c-d1ea-48ba-8d62-ebdd39d87e11)

**Comment by Poryaei** [comment]
Please use the updated version. 🔄
