### ISSUE TITLE
Invalid request for submit_taps function

### ISSUE THREAD

**Issue by arashm404** [Poryaei/TapSwap-Clicker#18]
Hi
thank you for your codes
there is problem with submit_taps even also added content-id 
sometimes result is {"statusCode":400,"message":"invalid_request[2]"}
any solutions?

**Comment by Poryaei** [comment]
Problem solved in the update! 👍🏻

**Comment by arashm404** [comment]
while True:
        try:
            response = session.post('https://api.tapswap.ai/api/player/submit_taps', headers=headers, json=payload).json()
            break
        except Exception as e:
            print("[!] Error in Tapping: ", e)
            time.sleep(2)
    return response
    
    but you did not print(response)
    print the response and you will see this message
