### ISSUE TITLE
[!] Error in auth:   'player'

### ISSUE THREAD

**Issue by yopiucing** [Poryaei/TapSwap-Clicker#22]
![IMG_20240529_125958](https://github.com/Poryaei/TapSwap-Clicker/assets/116066417/62097c03-bf77-47ff-9205-ce2cfea7ad34)

**Comment by Poryaei** [comment]
Are you using the latest version?

**Comment by yopiucing** [comment]
> Are you using the latest version?

i am using the 1.6 version

**Comment by Poryaei** [comment]
Ok pls update again and try

**Comment by yopiucing** [comment]
> Ok pls update again and try

thanks, it's working
