### ISSUE TITLE
خارج شدن از اسکریپت

### ISSUE THREAD

**Issue by ppouria** [Poryaei/TapSwap-Clicker#24]
درود ابولفضل جان
ممنون از راهنمایی که کردی مشکلم حل شد و ربات به درستی داره کار میکنه
یک سوالی داشتم این بود که من با لینکوس اینکارو کردم روی سرور مجازی 
الان اگه ctrl + c بزنم از اسکریپت خارج میشه.
این ربات باز هم کار میکنه؟
![image](https://github.com/Poryaei/TapSwap-Clicker/assets/168307391/e13c99ba-21f9-4a95-8cc7-9a311b6e4289)

**Comment by Poryaei** [comment]
سلام وقت بخیر
نه! میتونی از screen استفاده کنی

screen python3 clicker.py

**Comment by ppouria** [comment]
درسته!
خیلی ممنون از راهنمایی شما.
روی هاست هم میشه این رو ران کرد؟

**Comment by Poryaei** [comment]
خواهش میکنم. زیاد اطلاعی از اجرای اسکریپت پایتون در هاست ندارم ولی طبیعتا اجازه دسترسی به ترمینال بدن یا اجازه اجرای کد پایتون رو بهت بدن میشه احتمالا اسکریپت رو اجرا کرد.
