### ISSUE TITLE
[!] Error in auth:   'player' "same error again, i am using latest version"

### ISSUE THREAD

**Issue by yopiucing** [Poryaei/TapSwap-Clicker#29]
![IMG_20240530_221437](https://github.com/Poryaei/TapSwap-Clicker/assets/116066417/473d8197-a805-4570-af7a-844619a563b0)

**Comment by naseria1364** [comment]
same error today

**Comment by Poryaei** [comment]
![image](https://github.com/Poryaei/TapSwap-Clicker/assets/83473475/3ddc11f3-2d7f-4b69-a62f-a7dae52141a2)
TapSwap server error!

**Comment by Poryaei** [comment]
And dont use script 
Wait for update

https://github.com/Poryaei/TapSwap-Clicker/issues/28

**Comment by abolfazlMKazemi** [comment]
hi i update code but get this error 
[!] Error in auth:   'player'

**Comment by nobiskriper** [comment]
I have a different error on my end.
![image](https://github.com/Poryaei/TapSwap-Clicker/assets/171317293/43080cd5-0bff-4817-800c-34c02a8fa770)

**Comment by Poryaei** [comment]
Update the script, there shouldn't be any problem. 👍
