### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by ppouria** [Poryaei/TapSwap-Clicker#31]
![image](https://github.com/Poryaei/TapSwap-Clicker/assets/168307391/052b04d0-f148-4d45-a2b5-03dc5b88b952)

**Comment by RoseGoli** [comment]
Just a bug due to lack of sleep 😂

**Comment by Poryaei** [comment]
@Poruai1928 
Hi pls install cloudscraper
python3 -m pip install cloudscraper
