### ISSUE TITLE
[!] Error in X-CV: list index out of range

### ISSUE THREAD

**Issue by yopiucing** [Poryaei/TapSwap-Clicker#35]
![IMG_20240601_165316](https://github.com/Poryaei/TapSwap-Clicker/assets/116066417/73ed8e0c-8f52-4f19-b747-a9721c87e073)

**Comment by THMaST3R** [comment]
tapswap bot is down

**Comment by yopiucing** [comment]
> tapswap bot is down

but i can open it on my phone

**Comment by Poryaei** [comment]
Hi update tapswap.py
