### ISSUE TITLE
[!] Error in X-CV: list index out of range

### ISSUE THREAD

**Issue by THMaST3R** [Poryaei/TapSwap-Clicker#36]
[!] Error in X-CV: list index out of range
[!] Error in X-CV: list index out of range
[!] Error in X-CV: list index out of range
[!] Error in X-CV: list index out of range
[!] Error in X-CV: list index out of range
[!] Error in X-CV: list index out of range
[!] We ran into trouble with the updates to the headers! 🚫 The script is stopping.

after new update

**Comment by RoseGoli** [comment]
it will be fixed soon :)

**Comment by Poryaei** [comment]
Please update the file tapswap.py, there should be no issue.
