### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Kingprogrammer07** [Poryaei/TapSwap-Clicker#37]
[!] Error in X-CV: list index out of range
[!] We ran into trouble with the updates to the headers! 🚫 The script is stopping.

**Comment by RoseGoli** [comment]
working on it, will be fixed soon

**Comment by Poryaei** [comment]
Please update the file tapswap.py, there should be no issue.

**Comment by Kingprogrammer07** [comment]
Thanks
