### ISSUE TITLE
[!] We ran into trouble with the get auth token! 🚫 The script is stopping.

### ISSUE THREAD

**Issue by THMaST3R** [Poryaei/TapSwap-Clicker#39]
Client is Ready!
{'accept': '*/*', 'accept-language': 'en-US,en;q=0.9,fa;q=0.8', 'content-type': 'application/json', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-site', 'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13; iPhone 15 Pro Max) AppleWebKit/533.2 (KHTML, like Gecko) Version/122.0 Mobile/15E148 Safari/533.2', 'Authorization': 'Bearer ', 'x-cv': '617', 'X-App': 'tapswap_server', 'x-bot': 'no', 'Content-Type': 'application/json', 'Referer': 'https://app.tapswap.club/', 'x-app': 'tapswap_server'}[!] There is no access_token in response
[!] There is no access_token in response
[!] There is no access_token in response
[!] There is no access_token in response
[!] There is no access_token in response
[!] There is no access_token in response
[!] We ran into trouble with the get auth token! 🚫 The script is stopping.

**Comment by THMaST3R** [comment]
on latest version

**Comment by Poryaei** [comment]
Update pls

**Comment by amirhosene** [comment]
سلام دوت عزیز این ارور بعد هر 24 ساعت میاد من اپدیت کردم باز همین ارور میاد و مجبورم دوباره ران کنم
