### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abolfazlMKazemi** [Poryaei/TapSwap-Clicker#40]
Hi thanks for code i get this error
[!] Error in auth: Expecting value: line 1 column 1 (char 0)
[!] Error in auth: Expecting value: line 1 column 1 (char 0)
[!] Error in auth: Expecting value: line 1 column 1 (char 0)
[!] Error in auth: Expecting value: line 1 column 1 (char 0)
[!] Error in auth: Expecting value: line 1 column 1 (char 0)
[!] Error in auth: Expecting value: line 1 column 1 (char 0)
[!] We ran into trouble with the get auth token! 🚫 The script is stopping.

**Comment by Poryaei** [comment]
TapSwap is currently under maintenance and updates. The issue is not from the code. 🛠️
https://t.me/tapswapai/121
