### ISSUE TITLE
click time

### ISSUE THREAD

**Issue by ppouria** [Poryaei/TapSwap-Clicker#41]
درود ابولفضل جان
درحال حاضر تایم هر کلیک به 30 دقیقه افزایش یافته درسته؟
بنابر این برای اینکه ساعتی 20 هزارتا ماین بشه نیاز هست که مخزن تا لول 20 اپگرید بشه
این درسته؟

**Comment by Poryaei** [comment]
سلام پوریا جان 
نه! در اصل یک مقدار بیشتر از زمانی که مخزن وقت میبره پر بشه ( بین 2 تا 12 دقیقه به صورت رندوم )
و مهم نیست که مخزن شما چقدر باشه! بیشتر مهم سرعت پر شدن اون مخزن هست و مخزن لول بالا بیشتر توی boost ها تاثیر میزاره
