### ISSUE TITLE
How can I speed up the bot even though I will lose bot detection protection?

### ISSUE THREAD

**Issue by finalsecure** [Poryaei/TapSwap-Clicker#42]
I only want the bot to wait for it to regenerate when it runs out of energy, not for anything else, and for the clicks to be fast enough that I can do it with a simple clicker app on the phone.

I have some knowledge of Python, but it would be safer for me to follow the developer's instructions on which parts of the code I should change.

Thanks...

**Comment by Poryaei** [comment]
Hi

tapswap.py

Line 384: remove ` + random.randint(60*2, 60*12)`
