### ISSUE TITLE
Error in auth: list index out of range

### ISSUE THREAD

**Issue by danazor** [Poryaei/TapSwap-Clicker#43]
hi! I've been using your clicker for about a few days. I encountered an error this morning...

[!] Error in auth: list index out of range
[!] Error in auth: list index out of range
[!] Error in auth: list index out of range
[!] Error in auth: list index out of range
[!] Error in auth: list index out of range
[!] Error in auth: list index out of range
[!] We ran into trouble with the get auth token! 🚫 The script is stopping.

- I tried rewriting the readme commands and it didn't work.
- Tapswap servers are active now and I can connect when I control it from my mobile.

What can I do to fix this error? Thanks

**Comment by Poryaei** [comment]
Hello! Please use the latest update. 🔄
