### ISSUE TITLE
KeyError 3

### ISSUE THREAD

**Issue by danazor** [Poryaei/TapSwap-Clicker#44]
Hi again!  When i use the latest update i got this error

KeyError 3

after that i re download python and clicker but still not solve my problem

Thank you for your help

**Comment by Poryaei** [comment]
Hi use python 3.10

**Comment by danazor** [comment]
i delete python 3.12 than i install 3.10.0 but my problem is still continue

**Comment by Poryaei** [comment]
Screen shot pls

**Comment by danazor** [comment]
@Poryaei 
![Untitled-1](https://github.com/Poryaei/TapSwap-Clicker/assets/52712010/5a5242d0-be8c-496a-9a68-cb7f46d6639c)
![Untitled-2](https://github.com/Poryaei/TapSwap-Clicker/assets/52712010/5f277329-3823-4c46-a589-ee95273687e3)

**Comment by Poryaei** [comment]
run: python -v

**Comment by Poryaei** [comment]
![image](https://github.com/Poryaei/TapSwap-Clicker/assets/83473475/10e5b5d9-5449-4150-820e-1b6534c2cd3d)

Use 3.10

**Comment by danazor** [comment]
Used 3.10 but path direction was 3.11

So i changed paths and da daaa its solved.

Thank you
