### ISSUE TITLE
ImportError: cannot import name 'appengine' from 'urllib3.contrib'

### ISSUE THREAD

**Issue by dibbed** [Poryaei/TapSwap-Clicker#47]
![Annotation 2024-06-14 184839](https://github.com/Poryaei/TapSwap-Clicker/assets/26880378/e830cefd-800b-44c0-ba08-0fbe30df1a6b)

**Comment by deadnesshc** [comment]
im fix it buy new bug comes out

![Annotation 2024-06-14 184839](https://github.com/Poryaei/TapSwap-Clicker/assets/26880378/8abff86b-f824-45e6-b011-4c40d893ddac)

**Comment by dibbed** [comment]
fix it with :

pip3 install --upgrade requests-toolbelt urllib3 cloudscraper

pip3 uninstall urllib3
pip3 uninstall requests-toolbelt
pip3 install urllib3
pip3 install requests-toolbelt
