### ISSUE TITLE
What is the problem here ?

### ISSUE THREAD

**Issue by heykolog** [Poryaei/TapSwap-Clicker#8]
![hata](https://github.com/Poryaei/TapSwap-Clicker/assets/170169541/904f643f-199a-437c-9e0d-87641ad717be)

What is the problem here ?

**Comment by mrdarkerr** [comment]
me too
Time:  4.1961669921875e-05 S
1280.3333333333333
Time:  1.621246337890625e-05 S
1224.0
Time:  1.6927719116210938e-05 S
1167.6666666666667
